version: '2.1'

services:
  nginx:
    container_name: tyke-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:8081
    links:
      - tyke

  redis:
    image: redis
    ports:
      - 6379:6379

  tyke:
    image: mydocker/tyke:1.3-SNAPSHOT
    ports:
      - 9000:9000
    links:
      - redis
    volumes:
      - ./application.docker.conf:/tyke/etc/application.conf
